name = "JuSwalbe"
uuid = "eb6322ed-418d-497a-83f0-b052d1dea7c7"
authors = ["Stefan Zitz <physiknerd@gmail.com>"]
version = "0.1.0"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Expectations = "2fe49d83-0758-5602-8f54-1f90ad0d522b"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Documenter = "0.24"
Images = "0.22"
JSON = "0.21"

julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
